"""
Defines the core Pydantic data models for the Personalized Learning App.

This module contains the `KnowledgePoint` and `UserProgress` models,
which are fundamental to representing the learning content and user's
interaction with it.
"""
from typing import List, Dict, Any # Retained Any for flexibility in UserProgress.learning_history
from pydantic import BaseModel, Field
import uuid

class KnowledgePoint(BaseModel):
    """
    Represents a single point of knowledge or a learning topic within the graph.

    Attributes:
        id (str): A unique identifier for the knowledge point, generated by default.
        name (str): The name or title of the knowledge point (e.g., "Python Variables").
        description (str): A brief description of what this knowledge point covers.
        prerequisites (List[str]): A list of IDs of `KnowledgePoint`s that should be mastered
                                   before attempting this one.
        postrequisites (List[str]): A list of IDs of `KnowledgePoint`s that can be learned
                                    after mastering this one.
        explanation_prompt (str): A prompt to be used with an LLM to generate a detailed
                                  explanation of this knowledge point.
                                  Example for LLM: "Explain the concept of [name] in detail,
                                  covering its definition, importance, and key aspects."
        example_prompt (str): A prompt to be used with an LLM to generate a practical example
                              or use case for this knowledge point.
                              Example for LLM: "Provide a simple, clear code example (if applicable)
                              or a real-world scenario illustrating [name]."
        test_prompt (str): A prompt to be used with an LLM to generate test questions
                           or assessment criteria for this knowledge point.
                           Example for LLM: "Generate 2-3 test questions (e.g., multiple-choice,
                           short answer) to assess understanding of [name]. Include correct answers
                           or evaluation guidelines."
        mastery_threshold (float): The score (0.0 to 1.0) required to consider this
                                   knowledge point mastered by the user. Defaults to 0.80.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier for the knowledge point.")
    name: str = Field(..., description="Name or title of the knowledge point.")
    description: str = Field(..., description="Brief description of the knowledge point.")
    prerequisites: List[str] = Field(default_factory=list, description="List of prerequisite knowledge point IDs.")
    postrequisites: List[str] = Field(default_factory=list, description="List of postrequisite knowledge point IDs.")
    
    # LLM Prompts - reviewed for clarity
    explanation_prompt: str = Field(
        ..., 
        description="Prompt for LLM to generate an explanation. Should be specific to the KP's name and description."
    )
    example_prompt: str = Field(
        ..., 
        description="Prompt for LLM to generate an example. Should request code or real-world scenarios."
    )
    test_prompt: str = Field(
        ..., 
        description="Prompt for LLM to generate test questions. Should specify types and expected output."
    )
    
    mastery_threshold: float = Field(default=0.80, ge=0.0, le=1.0, description="Score needed to master this point (0.0-1.0).")


class UserProgress(BaseModel):
    """
    Tracks a user's progress and mastery level for a specific knowledge point.

    Attributes:
        user_id (str): The identifier for the user.
        knowledge_point_id (str): The ID of the `KnowledgePoint` this progress record refers to.
        mastery_level (float): The user's current mastery score for this knowledge point (0.0 to 1.0).
                               Defaults to 0.0.
        learning_history (List[Dict[str, Any]]): A log of learning activities undertaken by the user
                                                 for this knowledge point (e.g., test attempts,
                                                 content views). Each entry is a dictionary,
                                                 which could include keys like 'action', 'timestamp',
                                                 'score', 'details'. Defaults to an empty list.
    """
    user_id: str = Field(..., description="Identifier for the user.")
    knowledge_point_id: str = Field(..., description="ID of the related knowledge point.")
    mastery_level: float = Field(default=0.0, ge=0.0, le=1.0, description="User's mastery score (0.0-1.0).")
    learning_history: List[Dict[str, Any]] = Field(
        default_factory=list, 
        description="Log of learning activities for this knowledge point."
    )

# Example usage (not part of the module's operational code, but good for understanding):
if __name__ == "__main__":
    # This section is for demonstration and won't run during normal import
    kp_demo = KnowledgePoint(
        name="Introduction to Python",
        description="Learn the very basics of Python programming.",
        explanation_prompt="Explain what Python is, its history, common uses, and how to set up a Python environment. Describe basic syntax like variables, print statements, and comments.",
        example_prompt="Provide a 'Hello, World!' program in Python. Show how to declare a variable and assign it a string value, then print that variable.",
        test_prompt="Generate one multiple-choice question about Python's common uses and one short-answer question asking to write a simple print statement in Python."
    )
    print("--- Sample KnowledgePoint ---")
    print(kp_demo.model_dump_json(indent=2))

    up_demo = UserProgress(
        user_id="test_user_123",
        knowledge_point_id=kp_demo.id,
        mastery_level=0.75,
        learning_history=[
            {"action": "viewed_explanation", "timestamp": "2023-10-26T10:00:00Z"},
            {"action": "attempted_test", "score": 0.75, "timestamp": "2023-10-26T10:05:00Z"}
        ]
    )
    print("\n--- Sample UserProgress ---")
    print(up_demo.model_dump_json(indent=2))
